# Generated by Django 2.2 on 2020-06-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificateapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateapplication',
            name='employees_amount',
            field=models.CharField(choices=[('1-20', '1-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('101-200', '101-200'), ('> 200', 'Over 200'), ('NA', 'Not Available')], default='NA', max_length=10),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='turnover',
            field=models.CharField(choices=[('< 1M', 'Less than 1 000 000'), ('1M-5M', '1 000 000 - 5 000 000'), ('5M-50M', '5 000 000 - 50 000 000'), ('> 50M', 'Over 50 000 000'), ('NA', 'Not Applicable')], default='NA', max_length=10),
        ),
    ]
