# Generated by Django 2.2 on 2020-06-05 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ssm_registration_no', models.CharField(default='NA', max_length=255)),
                ('address_line_1', models.CharField(default='NA', max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=5)),
                ('city', models.CharField(default='NA', max_length=100)),
                ('state', models.CharField(default='NA', max_length=100)),
                ('country', models.CharField(default='NA', max_length=100)),
                ('ceo_name', models.CharField(default='NA', max_length=100)),
                ('organisation_name', models.CharField(default='NA', max_length=100)),
                ('organisation_phone', models.CharField(default='NA', max_length=100)),
                ('organisation_email', models.CharField(default='NA', max_length=100)),
                ('organisation_fax', models.CharField(default='NA', max_length=100)),
                ('is_large_organisation', models.BooleanField(default=False)),
                ('organisation_type', models.CharField(choices=[('GM', 'Government'), ('PM', 'Private (Malaysia)'), ('PF', 'Private (Foreign)'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('employees_amount', models.CharField(choices=[('1-20', '1-20'), ('21-50', '21-50'), ('51-100', '51-100'), ('101-200', '101-200'), ('> 200', 'Over 200'), ('NA', 'Not Available')], default='NA', max_length=2)),
                ('turnover', models.CharField(choices=[('< 1M', 'Less than 1 000 000'), ('1M-5M', '1 000 000 - 5 000 000'), ('5M-50M', '5 000 000 - 50 000 000'), ('> 50M', 'Over 50 000 000'), ('NA', 'Not Applicable')], default='NA', max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
