# Generated by Django 2.2 on 2020-06-04 00:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint_type', models.CharField(choices=[('IS', 'ICSB service'), ('MC', 'Misused of certificates mark'), ('IP', 'ISCB personal and external resources'), ('IC', 'ISCB client performance'), ('VC', 'Vulnerabilities of certified product or website'), ('NA', 'Not available')], default='NA', max_length=2)),
                ('description', models.CharField(default='NA', max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
