# Generated by Django 2.2 on 2020-06-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('IS', 'ICSB service'), ('MC', 'Misused of certificates mark'), ('IP', 'ISCB personal & external resources'), ('IC', 'ISCB client performance'), ('VC', 'Vulnerabilities of certified product or website'), ('NA', 'Not available')], default='NA', max_length=2),
        ),
    ]
